apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ./argocd/apps/
    repoURL: 'https://github.com/truemark/k8s-addons'
    targetRevision: feat/terraform-pipeline
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true