apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: argo-demo
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 11.1.14
    chart: mysql
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
