helmDefaults:
  createNamespace: true
  verify: true
  wait: true
  timeout: 300

repositories:
  - name: truemark
    url: public.ecr.aws/truemark
    oci: true

releases:
  - name: k8s-app
    namespace: k8s-app
    chart: truemark/k8s-app
    version: 0.0.1-rc
    values:
      - values.yaml