helmDefaults:
  createNamespace: true
  verify: true
  wait: true
  timeout: 300

repositories:
  - name: truemark
    url: https://github.com/truemark/helm-charts

releases:
  - name: k8s-app
    namespace: k8s-app
    chart: truemark/k8s-app
    values:
      - values.yaml