name: 'setup'

# The workflow should only trigger on pull requests merges to the main branch and any file changes to the defined path
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The environment to deploy to"

jobs:
  cluster-access:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ secrets.AWS_ASSUME_ROLE_DEPLOY }}"
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Setup Cluster Access
        run: |
          aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }} --region ${{ vars.AWS_DEFAULT_REGION }}
