on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The environment to deploy to"
      helmfilePath:
        required: false
        type: string
        description: "The path to the helmfile.yaml file"
        default: "helmfile.yaml"
      helmWorkDirectory:
        required: false
        type: string
        description: "The directory where the helmfile.yaml file is located"
        default: "helm"

jobs:
  helm-diff:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Helm Diff
        uses: helmfile/helmfile-action@v1.9.1
        with:
          helmfile-args: diff -f ${{ inputs.helmfilePath }}
          helmfile-workdirectory: ${{ inputs.helmWorkDirectory }}
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets
