name: 'helmfile'

# The workflow should only trigger on pull requests merges to the main branch and any file changes to the defined path
on:
  push:
    paths:
      - "helm/**"
      - ".github/workflows/helmfile.yml"
    branches:
      - main
  pull_request:
    paths:
      - "helm/**"
      - ".github/workflows/helmfile.yml"
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment: "stage"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ secrets.AWS_ASSUME_ROLE_DEPLOY }}"
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Setup Cluster Access
        run: |
          aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }} --region ${{ vars.AWS_DEFAULT_REGION }} --kubeconfig ./kubeconfig
          echo 'KUBE_CONFIG_DATA<<EOF' >> $GITHUB_ENV
          echo $(cat ./kubeconfig | base64) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          AWS_REGION: ${{ vars.AWS_DEFAULT_REGION }}

      - uses: helmfile/helmfile-action@v1.9.1
        with:
          helmfile-args: diff -f helmfile.yaml
          helmfile-workdirectory: helm
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets