on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The environment to deploy to"
      helmfilePath:
        required: false
        type: string
        description: "The path to the helmfile.yaml file"
        default: "helmfile.yaml"
      helmWorkDirectory:
        required: false
        type: string
        description: "The directory where the helmfile.yaml file is located"
        default: "helm"
      helmfileArgs:
        required: false
        type: string
        description: "The arguments to pass to helmfile"
        default: "diff"

jobs:
  helmfile:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ secrets.AWS_ASSUME_ROLE_DEPLOY }}"
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Setup Cluster Access
        run: |
          aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }} --region ${{ vars.AWS_DEFAULT_REGION }}

      - name: Helm Diff
        uses: helmfile/helmfile-action@v1.9.1
        with:
          helmfile-args: "${{ inputs.helmfileArgs }} -f ${{ inputs.helmfilePath }}"
          helmfile-workdirectory: ${{ inputs.helmWorkDirectory }}
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets
      
