on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  checks: write
  id-token: write
  contents: read
  pull-requests: write
  issues: read


jobs:
  setup-access-stage:
    name: setup access
    uses: ./.github/workflows/access.yml
    with:
      environment: "stage"
    secrets: inherit
  diff-stage:
    name: helm diff
    needs: setup-access-stage
    uses: ./.github/workflows/diff.yml
    with:
      environment: "stage"
    secrets: inherit
#  deploy-prod:
#    uses: ./.github/workflows/helmfile.yml
#    with:
#      environment: "prod"