on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  checks: write
  id-token: write
  contents: read
  pull-requests: write
  issues: read


jobs:
  deploy-stage:
    uses: ./.github/workflows/helmfile.yml
    environment: stage
#  deploy-prod:
#    uses: ./.github/workflows/helmfile.yml
#    with:
#      environment: "prod"