on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  checks: write
  id-token: write
  contents: read
  pull-requests: write
  issues: read


jobs:
  stage-helm:
    name: run helmfile
    uses: ./.github/workflows/helmfile.yml
    with:
      environment: "stage"
    secrets: inherit
  stage-terraform:
    name: run terraform
    uses: ./.github/workflows/terraform.yml
    with:
      environment: "stage"
    secrets: inherit
  stage-kubectl:
    name: run kubectl
    uses: ./.github/workflows/kubectl.yml
    with:
      environment: "stage"
    secrets: inherit