name: 'cluster'

# The workflow should only trigger on pull requests merges to the main branch and any file changes to the defined path
on:
  push:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"
    branches:
      - main
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker://truemark/terraform-aws-pipe:latest
      env:
        TF_INIT: "true"
        TF_DEBUG: "false"
        LOCAL_PATH: "terraform"
        DEBUG: "true"
    with:
      environment: "stage"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "${{ env.AWS_DEFAULT_REGION }}"
          role-to-assume: "${{ secrets.AWS_ASSUME_ROLE }}"
          role-session-name: "gh-actions-terraform"
