name: 'cluster'

# The workflow should only trigger on pull requests merges to the main branch and any file changes to the defined path
on:
  push:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"
    branches:
      - main
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment: "stage"
    container:
      image: docker://truemark/terraform-aws-pipe:latest
      env:
        TF_INIT: "true"
        TF_DEBUG: "false"
        LOCAL_PATH: "terraform"
        DEBUG: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ secrets.AWS_ASSUME_ROLE }}"
          aws-region: "us-east-2"
